Sprint 13
sarcazmatic/java-shareit pull request #1
Opened 2023-04-13 09:43 UTC by sarcazmatic

2023-04-13 14:39 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к работе.

2023-04-13 14:39 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exceptions/ErrorResponse.java
> +    String error;
Модификатор

2023-04-13 14:39 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    private final HashMap<Long, List<Item>> itemsByUserId = new HashMap<>();
А зачем 2 мапы? Вроде 1й достаточно, а то так дублируется куча информации
Кроме того, как уже писалось до этого, лучше указывать в значении интерфейс, а не реализацию, то есть 
    private final Map<Long, Item> items = new HashMap<>();

2023-04-13 14:39 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +                            || item.getDescription().toLowerCase().contains(searchText))
Можно воспользоваться библиотекой и использовать StringUtils.containsIgnoreCase

2023-04-13 14:39 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemDto.getName() != null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-04-13 14:39 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @NotNull (groups = Create.class)
Перед скобкой не нужен пробел

2023-04-13 14:39 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +    private final Set<String> usersByEmail = new HashSet<>();
Аналогично, зачем 2 коллекции?

2023-04-13 14:39 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +
Лишний пропуск

2023-04-13 14:39 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +
Лишний пропуск строки

2023-04-13 14:39 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
Над методами публичными отсутствует owweride

2023-04-13 19:33 UTC, sarcazmatic commented on src/main/java/ru/practicum/shareit/exceptions/ErrorResponse.java
> +    String error;
+

2023-04-13 19:39 UTC, sarcazmatic commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @NotNull (groups = Create.class)
+

2023-04-13 19:39 UTC, sarcazmatic commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +
+

2023-04-13 19:41 UTC, sarcazmatic commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +
+

2023-04-13 19:42 UTC, sarcazmatic commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
+

2023-04-14 18:19 UTC, sarcazmatic commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +    private final Set<String> usersByEmail = new HashSet<>();
+

2023-04-14 19:43 UTC, sarcazmatic commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemDto.getName() != null) {
+

2023-04-14 19:54 UTC, sarcazmatic commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +                            || item.getDescription().toLowerCase().contains(searchText))
+

2023-04-14 20:02 UTC, sarcazmatic commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    private final HashMap<Long, List<Item>> itemsByUserId = new HashMap<>();
+

2023-04-14 20:10 UTC, sarcazmatic commented
Давно ничего не отправлял на проверку, как дела?)

2023-04-15 08:04 UTC, Frilock approved these changes
Принял

2023-04-15 08:04 UTC, Frilock commented on pom.xml
> +			<version>3.12.0</version>
Версии лучше в properties выносить

2023-04-25 20:51 UTC, merged